# Started: 2022-11-08
# by Rodrigo García-López for Prof. Arias's Viral Analysis Group at IBt, UNAM, Cuernavaca, Mexico.
# Under GNU GPLv3 license
# This script is intended to get a long list of possible mutations and create a table containing SARS-CoV-2 which table has them and how many how many have them, based on tables generated by script Analyze_MexSARS_indels.R
# Test in R
# indir <- "02_Analyses/Week_BW.1-Except_Mexico/"
# suffix <- "_allMuts.tsv"
# list_of_muts <- "allMuts_inSet.tsv"

### LOAD INPUT AND FUNCTIONS ###
args <- commandArgs(trailingOnly=TRUE)
if (length(args) < 3) { # at least, two arguments should be included: <indir> <suffix> <list_of_mutations>
  stop("A minimum of 3 arguments are mandatory: Rscript Mutations_table.R <indir> <suffix> <list_of_mutations>", call.=FALSE)
}
indir <- as.character(args[1]) # Get the name of the directory (full path is optional)
suffix <- as.character(args[2])  # Get a string handle to read input files
list_of_muts <- as.character(args[3]) # get a 1-col table with the whole list of mutations (all mutations in files in indir should be included and derreplicated)

### MAIN ###
print("Input directory:")
print(indir)
files <- list.files(path=indir) # list all files in the input directory
files <- files[grep(suffix, files)] # get only those matching the suffix
if (length(files) < 1) { # abort if no files were found
  stop("No files found in provided input dir with that suffix", call.=FALSE)
}
df <- read.table(list_of_muts, sep="\t",header=FALSE, skip=0, comment.char='',quote="",fill=FALSE, check.names=FALSE, stringsAsFactors=FALSE) # Load the expected mutations in all files (this should be created a priori)
# dim(df)
# [1] 43407     1
df[,"pos"] <- as.numeric(gsub("-","",gsub("[A-Z]","",df[,1]))) # Add a new column with the actual position
df <- df[!is.na(df[,"pos"]),] # Remove any NAs from the list
df <- df[order(df[,2]),] # and sort them by genomic position

output_abs <- matrix(0,ncol=length(files),nrow=nrow(df)) # Create void matrix container for all possible mutations and input files to be tested (absolute observations)
colnames(output_abs) <- gsub(suffix,"",files) #rename cols and rows in the output
rownames(output_abs) <- df[,1]
output_rel <- output_abs # and copy the matrix for a second one with relative numbers instead

dir.create("03_Mut_tables", showWarnings=FALSE)
print("Processing file:")
for(i in 1:length(files)){
	print(files[i])
	df2 <- read.table(paste(indir,files[i],sep="/"), sep="\t",header=TRUE, skip=0, comment.char='',quote="",fill=FALSE, check.names=FALSE, stringsAsFactors=FALSE)
	for(j in 1:nrow(df2)){
# 		print(j)
		output_abs[df2[j,1],i] <- df2[j,2]
		output_rel[df2[j,1],i] <- df2[j,3]
	}
}
filter_min_obs <- rowSums(output_abs)>=5
output_abs <- output_abs[filter_min_obs,]
output_rel <- output_rel[filter_min_obs,]
write.table(output_abs,paste0("03_Mut_tables/",basename(indir),"_Mutations-abs.tsv"), sep="\t", quote=FALSE, row.names=TRUE, col.names=NA)
write.table(output_rel,paste0("03_Mut_tables/",basename(indir),"_Mutations-rel.tsv"), sep="\t", quote=FALSE, row.names=TRUE, col.names=NA)

# Some extra filters
temp <- grep("N$",rownames(output_abs)); if(length(temp)>0){output_abs <- output_abs[-temp,]} # Remove Ns
temp <- grep("-$",rownames(output_abs)); if(length(temp)>0){output_abs <- output_abs[-temp,]} # Remove Deletions
temp <- grep("N$",rownames(output_rel)); if(length(temp)>0){output_rel <- output_rel[-temp,]} # Remove Ns
temp <- grep("-$",rownames(output_rel)); if(length(temp)>0){output_rel <- output_rel[-temp,]} # Remove Deletions

# and print the filtered tables
write.table(output_abs,paste0("03_Mut_tables/",basename(indir),"_Mutations-abs_only_snps.tsv"), sep="\t", quote=FALSE, row.names=TRUE, col.names=NA)
write.table(output_rel,paste0("03_Mut_tables/",basename(indir),"_Mutations-rel_only_snps.tsv"), sep="\t", quote=FALSE, row.names=TRUE, col.names=NA)


